### ISSUE TITLE
g_clear_error in glib gir file is missing a parameter

### ISSUE THREAD

**Issue by MARTIMM** [gircore/gir-files#103]
XML part shown below is from glib-2.0.gir;
```
<function throws="1" c:identifier="g_clear_error" name="clear_error">
      <doc filename="glib-2.0.c" line="13900" xml:space="preserve">If @err or *@err is %NULL, does nothing. Otherwise,
calls g_error_free() on *@err and sets *@err to %NULL.</doc> 
      <source-position line="239" filename="gerror.h"/> 
      <return-value transfer-ownership="none">
        <type c:type="void" name="none"/> 
      </return-value> 
    </function>
```
It misses a parameter definition for the `err` argument. In `gerror.h` it is declared as `void g_clear_error (GError **err);`.

**Comment by badcel** [comment]
The Gir file is correct as it is taken directly from the gnome sdk.

Regarding your remark: The `throws` attribute indicates that there is an error parameter which is not part of the parameter list.

You can find a complete definition of available attributes including description in [gir-1.2.rnc](https://gitlab.gnome.org/GNOME/gobject-introspection/-/blob/main/docs/gir-1.2.rnc).

**Comment by MARTIMM** [comment]
Thank you for your answer. I'm afraid I do not understand your explanation. In the link you provided above I found the following text
```
    ## Binary attribute, true if the callable can throw an error
    attribute throws { "0" | "1" }?,
```
This tells something about the behavior of the function but not about the parameters.
Also, the doc element tells something about `@err`, the argument to the function. How to provide it when there is no argument list?

**Comment by badcel** [comment]
Yeah the documentation is lacking a bit. The `throws=1` simply means that there is an error parameter even if it is not visible in the parameter list. If you generate some code you have to add the error parameter otherwise it would not work.

Unfortunately I can’t tell you the reason for this decision, as it was made by the GObject developers. But you can contact them on matrix too in #introspection:gnome.org

**Comment by MARTIMM** [comment]
Found a way around using your remarks. Thanks for the pointers  mentioned above.
